# Generated by Django 5.2.1 on 2025-11-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_type', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('post_description', models.TextField()),
            ],
        ),
    ]
