# Generated by Django 5.2.1 on 2025-11-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_post1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post1',
            table='basic_post',
        ),
    ]
