# Generated by Django 5.2.1 on 2025-11-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(),
        ),
    ]
